---
title: "CV"
format: html
editor: visual
---

## Current Position

-   PhD Student at the Department of Botany, Faculty of Science, Charles University

## Education

-   2020 - 2022: Master's in Botany, Bishop Heber College, Bharathidasan University, Tamil Nadu, India

-   2017 - 2020 - Bachelor's in Plant Biology and Plant Biotechnology, Madras Christian College, University of Madras, Tamil Nadu, India.

## Work Experience 

-   2022: Master's Academic Project; Goa University

    -   Conducted Phenological Studies of Trees in Socorro Plateau, Goa.  The project involved studying the phenological patterns of various trees in Socorro plateau, by plotting their flowering, fruiting and leafing growth patterns and also understanding the various inter-connections which exist in between the different flora of the region.

-   2022: Internship; project run by Institute of Botany, Czech Academy of Sciences

    -   Assisted in the sampling of plant material from high elevations of Western Himalayas for belowground and aboveground trait measurements, soil sampling and processing of collected samples. The research work was conducted as part of a Horizon 2020 project entitled “Functional differentiation in response to environmental variability in two contrasting shrub line species of high-altitude Himalaya.”

## Conferences 

-   52^nd^ Annual conference of the Ecological Society of Germany, Austria and Switzerland (GfÖ) hosted by the German Centre for Integrative Biodiversity Research (iDiv) Halle-Jena-Leipzig; Presented a poster entitled “Effects of Changes in Soil Nutrient and Water Availability on Floral Economic Spectrum” under session “Traits and Stability” on 12^th^ & 13^th^ September, 2023.

-   International Conference on Climate Change Adaptation for Sustainable Biodiversity and Food Security organized by the Department of Zoology and Research Centre, Scott Christian College (Autonomous), Nagercoil, Tamil Nadu, India; Presented a paper entitled “Investigation into the Phenological Patterns of Trees in Socorro Plateau, Goa” on 23rd & 24th June, 2022 and was awarded Best Oral Presentation Award under the subtheme “Biodiversity”.

-   National Seminar on Innovative Research Approaches in Biological Sciences organized by PG and Research Department of Botany, Jamal Mohamed College, Tiruchirappalli, Tamil Nadu, India and presented a paper entitled “Phenological Studies of Trees in Socorro Plateau, Goa” on 25th & 26th May, 2022.

-   International Conference on Climate Adaptation and Resilience organized by Department of Environmental Sciences, Bishop Heber College, Tiruchirappalli, Tamil Nadu, India and presented a paper entitled “Aphid – Ant Interactions in Different Plant Species” on 22nd & 23rd April, 2022.

## Supervised students 

-   Bidhan Panthi (Masters, co-supervision, finished)

-   Tereza Kratochvílová (Open Science, supervision, finished)

-   Filip Kreuter (Open Science, supervision, finished)

-   Marketa Prusova (Bachelors, co-supervision, ongoing)

-   Myrtille Leleu (Masters, supervision, ongoing)

-   Katerina Gourlay (Open Science, supervision, ongoing)

-   Sofie Gabriela Šalamounová (Open Science, supervision, ongoing)

## Other Participation

-   Attended Workshop on quantitative ecology titled, “School of Quantitative Ecology 2024 (SSoQE2024)” at the ecological outstation of the University of Bayreuth in Wallenfels, Germany from 23.09.2024 to 29.09.2024.

-   Worked as volunteer and attended the 53nd annual conference of the Ecological Society of Germany, Austria and Switzerland (GfÖ) hosted by the Technical University of Munich’s Weihenstephan campus in Freising from 9-13 September, 2024.

-   Worked as volunteer in the 52^nd^ annual conference of the Ecological Society of Germany, Austria and Switzerland (GfÖ) hosted by the German Centre for Integrative Biodiversity Research (iDiv) Halle-Jena-Leipzig from 11-16 September, 2023.

-   Online Workshop on ‘Plant Inventory Methods – I’ organized by Manipal Centre for Natural Sciences, Manipal, Karnataka, India on 14th and 15th February, 2021.

-   Online Training Program under the theme of ‘Botany & Plant Biotechnology’ organized by CSIR – Indian Institute of Integrative Medicine, Jammu, India. This training program was conducted under the scheme “CSIR-Integrated Skill Initiative Program” from August, 2021 to October, 2021.

-   Online Summer Training Program in Biological Sciences organized by Academy of Sciences, Chennai in association with Department of Zoology, University of Madras, Chennai, Tamil Nadu, India from July, 2021 to August, 2021.

-   Online Workshop on Restoration Ecology and People’s Participation organized by Department of Zoology, Madras Christian College, Chennai, Tamil Nadu, India on 18th and 19th August, 2021.

-   Hands on Training in Seaweed Cultivation and Processing Technology organized by CSIR-CSMCRI, Bhavnagar at CSMCRI – Marine Algal Research Station, Mandapam Camp, Tamil Nadu, India. This training program was conducted under the scheme “CSIR-Integrated Skill Initiative Program” from 17th to 19th March, 2021.
